/* ----- DATABASE CONFIGURATION ----- */

ChannelDatabase=[
['','** Comedy **'],
['', 'Spagoots: Top Ten Face-Off'],
['https://www.youtube.com/watch?v=UUAKMHKCu2g', 'Top Ten Steven Universe Characters!'],
['https://www.youtube.com/watch?v=5sjGZzUyoCA', 'Top Ten Pixar Films'],
['https://www.youtube.com/watch?v=y7-QQNM00JA', 'Top Ten Disney Films'],
['https://www.youtube.com/watch?v=NQkxNw7zgP4', 'Top Ten Animated Villains'],
['', 'Memes'],
['https://www.youtube.com/watch?v=bxLnT5TJjow', 'MLG Mario'],
['https://www.youtube.com/watch?v=-4jwzan3AyA', '149 Internet Memes in 300 Seconds'],
['https://www.youtube.com/watch?v=dQw4w9WgXcQ', 'Never Gonna Give You Up'],
['https://www.youtube.com/watch?v=QH2-TGUlwu4', 'Nyan Cat'],
['https://www.youtube.com/watch?v=Mh5LY4Mz15o', 'history of japan'],
['https://www.youtube.com/watch?v=_j1-xQA_ufE', 'Diemon Dave Ninja School'],
['https://www.youtube.com/watch?v=UlzoL-wQwio', 'i-Gun Traffic Rampage'],
['https://www.youtube.com/watch?v=G-Wn48geCJ8', 'Racist Mario'],
['https://www.youtube.com/watch?v=2HQaBWziYvY', 'Darude - Sandstorm'],
['http://youtube.com/watch?v=3NmeUMIialw', 'Dogsongs: A Dogsong Medley'],
['','** Music **'],
['', 'UNDER THE TALE: A UNDERTALE Remix Album'],
['https://www.youtube.com/watch?v=5fkKJ_XzBFA', 'Battle Against A Sprite Hero'],
['https://www.youtube.com/watch?v=2vh0uZKUN5Y', 'Bone Cold'],
['https://www.youtube.com/watch?v=etoe5hoahy4', 'SAVE The Fallen'],
['https://www.youtube.com/watch?v=TP-_1iyD8LE', 'MEGADUNKED'],
['', 'MandoPony'],
['http://youtube.com/watch?v=C8kOhbTe1So', '"This Far" - Pokémon song'],
['http://youtube.com/watch?v=U7IzkME9qXA', '"Something Strange" - Luigi\'s Mansion song'],
['http://youtube.com/watch?v=JgFNf4nLGNk', '"Just 3 Days" - The Legend of Zelda: Majora\'s Mask song'],
['http://youtube.com/watch?v=eZ8iMcqF4vs', 'Splatoon Final Boss REMIX (Feat. Callie + Marie)'],
['http://youtube.com/watch?v=ZB6RHqoAvJU', '"I Ink Therefore I Am" - Splatoon Song'],
['http://youtube.com/watch?v=QM3hpHE28hw', '"Chara" ► UNDERTALE SONG [Genocide]'],
['http://youtube.com/watch?v=5_wjZUbIFSw', '"Immortals Will Fall" - Castlevania Rock Song'],
['http://youtube.com/watch?v=hEcpcA2UTcw', 'MEGALOVANIA - Rock Cover [UNDERTALE]'],
['http://youtube.com/watch?v=um0vCASb9ec', '"Inside of Me" - StarFox rock song'],
['http://youtube.com/watch?v=xWnXsUSFVa8', '"Fade Away" - UNDERTALE song'],
['http://youtube.com/watch?v=dROG7UBRg6Q', '"Fighter" - Little Mac RAP | Punch-Out!!'],
['http://youtube.com/watch?v=Ru-x3CFQ97E', '"They Need a Monster" - UNDERTALE SONG! [Ft. Mettaton EX]'],
['http://youtube.com/watch?v=VtotCj7ovkU', '"Turning Over a New Leaf" - Animal Crossing Song [Ft. Emily Jones]'],
['http://youtube.com/watch?v=mKYEk3TkUW8', '"My Home" - Gravity Falls Song'],
['', 'V/T/S - Voice/Text/Song'],
['http://youtube.com/watch?v=rOmW2n0EjZc', 'Stronger Than You'],
['http://youtube.com/watch?v=zghPOtiKXmU', 'We Are The Crystal Gems'],
['http://youtube.com/watch?v=6dGKZPsG_RM', 'Feel Good Inc.'],
['http://youtube.com/watch?v=mi-vgbgJezM', 'Strong In The Real Way'],
['http://youtube.com/watch?v=EzfbVNcpm60', 'All Star'],
['http://youtube.com/watch?v=XQoN2q6saH4', '2,000 Subscriber Surprise'],
['http://youtube.com/watch?v=PU9NaBWpLcA', 'Good Feeling (feat. Celine Ellicott)'],
['http://youtube.com/watch?v=mr4kxn9Uy9I', 'This Is Gospel'],
['https://www.youtube.com/watch?v=nwj7xiCCMOw', 'We Are The Crystal Gems (Full Version)'],
['https://www.youtube.com/watch?v=1m5WrzPwh-I', 'Find A Pet'],
['', 'Star Shop by Chongo'],
['http://youtube.com/watch?v=aDc8VaXe5_I', '1 - Combined Star'],
['http://youtube.com/watch?v=_CqeD72xrWY', '2 - Burning Star'],
['http://youtube.com/watch?v=cisisEw89Y4', '3 - Improved Star'],
['http://youtube.com/watch?v=CkqnOQZIn0k', '4 - Disconnected Star'],
['http://youtube.com/watch?v=9_BQgn3Ic-0', '5 - Laughing Star'],
['http://youtube.com/watch?v=6asUL1he-kQ', '6 - Spaghetti Star'],
['http://youtube.com/watch?v=W-36Hwym2XY', '7 - Party Star'],
['http://youtube.com/watch?v=UaJBDjGkCrM', '8 - Cake Star'],
['http://youtube.com/watch?v=ZuX-FPrpJiM', '9 - Romantic Star'],
['http://youtube.com/watch?v=_twcGtJbBpc', '10 - Wonder Star'],
['http://youtube.com/watch?v=56VsJiL8wOs', '11 - Healing Star'],
['http://youtube.com/watch?v=7rSiHStJUHg', '12 - Adventure Star'],
['http://youtube.com/watch?v=PI-eBGL4Ysw', '13 - Nostalgic Star'],
['http://youtube.com/watch?v=PTw6xShL2Jw', '14 - Bowling Star'],
['http://youtube.com/watch?v=SSezmdDYCho', '15 - Deer Star'],
['http://youtube.com/watch?v=jpjgCzflzgA', '16 - Christmas Star'],
['http://youtube.com/watch?v=lW9AQ3ftg3U', '17 - Descending Star'],
['http://youtube.com/watch?v=KA_zkTYXE_g', '18 - Dedicated Star'],
['http://youtube.com/watch?v=7JpK1jpQxMA', 'Bonus - The One With The Bassline'],
['', 'UNDERTALE: The Underground Radio by DM DOKURO'],
['http://youtube.com/watch?v=Xg2eYFNSPBU', 'BONESCUFFLE'],
['http://youtube.com/watch?v=n-FUV3Aleug', '[MASSIVE SPOILERS] SAVE'],
['http://youtube.com/watch?v=evCV4gNr4Gk', '[MASSIVE SPOILER MILESTONE] SAVE (Encore)'],
['http://youtube.com/watch?v=baV-6-oHnA8', '[Neutral Spoilers] g a r d e n'],
['http://youtube.com/watch?v=lsJdj92ZlXo', 'Sign Language'],
['http://youtube.com/watch?v=CEI_jZbLLj4', 'Dapper Mannequin Bakery'],
['http://youtube.com/watch?v=495MUfrcbMc', '[Genocide Spoilers] Reality Check Through The Skull'],
['http://youtube.com/watch?v=LUcovUfA9So', '[Neutral Spoilers] uNDeRWoRLD MoNaRCHy'],
['https://www.youtube.com/watch?v=WAxnbQK1zFw','[Genocide Spoilers] Reality Check Through The Skull (Percussionless Challenge)']
['', 'Various Music'],
['http://youtube.com/watch?v=740W3kpAJD0', 'Edvard Grieg - In the Hall of the Mountain King (Deficio Remix)'],
['http://youtube.com/watch?v=46QX2hTGwPs', 'Shawn Wasabi - Pizza Rolls'],
['http://youtube.com/watch?v=BgfcToAjfdc', 'Kygo - Stole The Show feat. Parson James'],
['http://youtube.com/watch?v=e_VaDyN-5Ko', 'Parry Gripp - The Girl At The Video Game Store (feat. Olivia Munn and Kevin Pereira)'],
['http://youtube.com/watch?v=bE47er6qnqg', 'Nero - Me And You'],
['http://youtube.com/watch?v=_TWisxgZkBA', 'OSI Music - FOX Affilliate News Theme'],
['http://youtube.com/watch?v=bCjOSIUygLA', 'HBO - Feature Presentation'],
['http://youtube.com/watch?v=enYl_DFISF4', 'TechTV - Call For Help Theme Song'],
['http://youtube.com/watch?v=AU_p_8pXiF4', 'BIGBANG & PSY & 2NE1 - I AM FANTASTIC GANGNAM STYLE BABY'],
['http://youtube.com/watch?v=-EBcMGLhRAE', 'Knitting Giant Beanies - Insanity [McGucket/Bill Cipher Rap]'],
['http://youtube.com/watch?v=AppOiULLMDk', 'Holder - Megalovania (Undertale Remix)'],
['http://youtube.com/watch?v=cHcVU5cGUNE', 'Italobrothers - Stamp on the ground'],
['http://youtube.com/watch?v=-PSP2Adz5j8', 'The Lab Rats - Devil\'s Train'],
['http://youtube.com/watch?v=Wv24uMoGUZA', 'Massive Attack - Teardrop (The Chemical Brothers Remix)'],
['http://youtube.com/watch?v=BsGnMpSVixg', 'Calvin Harris - Outside ft. Ellie Goulding (Savagez Remix)'],
['http://youtube.com/watch?v=_IrQHeDcMi8', 'LunchMoney Lewis - Bills (Official Video)'],
['https://soundcloud.com/extremesomething/slow-down-deadmau5', 'Deadmau5 - Slow Down: Full Mix (Pre-Release)'],
['https://soundcloud.com/dragonxvi/bones-to-pick-undertale-boss-medley', 'DragonXVI - Bones To Pick (Undertale Boss Medley)'],
['https://soundcloud.com/boovox/jacksepticeye-25k', 'BooVox - JackSepticEye (25k subs REMIX)'],
['http://youtube.com/watch?v=zOqMIifjgWM', 'ZUU Music - Ne Pas Soumettre (Do Not Submit)'],
['http://youtube.com/watch?v=2CsMu0U3IHs', 'Mitchell Claxton - Doge'],
['http://youtube.com/watch?v=73jRDoeWZlw', 'The Living Tombstone - Spooky Scary Skeletons (Extended Mix)'],
['http://youtube.com/watch?v=V7QgOYB1Up4', 'BasslineKicker - An Eternity\'s End (Continuous Mix)'],
['http://youtube.com/watch?v=XWAaYe1fPjA', 'Nitro Fun - Dragonfly'],
['http://youtube.com/watch?v=0MD4Rblw2IE', 'Getsix - Pulse VIP'],
['http://youtube.com/watch?v=iYx84cQujR4', 'Gammer - Pigface ►±◄ (Dougal & Gammer Edit)'],
['http://youtube.com/watch?v=g-RY4xgLxSQ', 'Kontinuum - Lost (feat. Savoi)'],
['http://youtube.com/watch?v=tHSAyijQp4I', 'Kalm Koaz - White Rabbit (feat. Trinity) (Lets Be Friends Remix)'],
['http://youtube.com/watch?v=b_C3pK6MN6c', 'Shawn Wasabi - Mac n\' Cheese'],
['http://youtube.com/watch?v=6PkRRkbnXCc', 'BasslineKicker & Ufis - Requiem (BimHerty Remix)'],
['http://youtube.com/watch?v=s5bsNzE6xVc', 'Kill Paris - I Do Love You'],
['http://youtube.com/watch?v=nVaWJwU-sG0', 'MONSTA - Holdin\' On (Skrillex & Nero Remix)'],
['http://youtube.com/watch?v=_-dCAGbbzK0', 'Virtual Riot - Preset Junkies'],
['http://youtube.com/watch?v=kp_h6Ekm9qw', 'Getsix - The Time Traveller (Similar Outskirts Remix)'],
['http://youtube.com/watch?v=_x2gXWpDTco', 'Panda Eyes - On My Own'],
['http://youtube.com/watch?v=SZnTdz4qh2c', 'Pegboard Nerds - Casanovan \'13'],
['http://youtube.com/watch?v=nYsCR8Lrr5Q', 'BasslineKicker & Ufis - Requiem'],
['http://youtube.com/watch?v=P1CbstcJOMU', 'Subtact - Splinter'],
['http://youtube.com/watch?v=10cXiNIVEUo', 'nanobii - HYPER★DRIVE'],
['http://youtube.com/watch?v=AML-2BchC-E', 'Will & Tim vs Ephixa - Stone Tower Temple'],
['http://youtube.com/watch?v=L_hlKpxyS_E', 'Mssingno - XE3 (Wheathin Turn)'],
['http://youtube.com/watch?v=5oJusn92JAQ', 'Savant - Sledgehammer'],
['http://youtube.com/watch?v=Eq7UVBsqMQI', 'Porter Robinson - Flicker (Nitro Fun Remix)'],
['http://youtube.com/watch?v=bcFvsQhKfpA', 'Hellberg - Slumber Party'],
['http://youtube.com/watch?v=CsTL-fx1fGs', 'Porter Robinson - Sea Of Voices (Ninth Parallel Remix)'],
['http://youtube.com/watch?v=gSxn08RlcGA', 'Mewnlight Rose - Meteorite (Waking Dreams Remix)'],
['http://youtube.com/watch?v=BzCIpMv59Qo', 'Entity - Eternity'],
['http://youtube.com/watch?v=mawalFwDvc0', 'Dunderpatrullen - To The Moon (feat. FantomenK)'],
['http://youtube.com/watch?v=IrNz29OwWKg', 'SirensCeol - The Devil\'s Swing'],
['http://youtube.com/watch?v=QNc4XFfS-Zs', 'Deon Custom - Ice Cream'],
['http://youtube.com/watch?v=9kpdOT2nZd8', 'Panda Eyes - Antipixel'],
['http://youtube.com/watch?v=nsZ_eSxGGjY', 'Erio - Error'],
['http://youtube.com/watch?v=_8qFQk3KOSY', 'Getsix - Conquest (VIP Mix)'],
['http://youtube.com/watch?v=94bEA2tCzY8', 'Slips & Slurs - Heartless (feat. Bright Lights)'],
['http://youtube.com/watch?v=KMDecD9hsUA', 'Dex Arson - Round One'],
['http://youtube.com/watch?v=ohn-aBbWz4g', 'TheFatRat - Windfall'],
['http://youtube.com/watch?v=W6wWdzJMuJU', 'Sushi Killer - Waifu Dream (Ephixa Remix)'],
['http://youtube.com/watch?v=HRKKQPBeBBo', 'Varien - Beyond The Surface (feat. Aloma Steele)'],
['http://youtube.com/watch?v=iSFpGn18Szo', 'K-391 - Nice Takeoff'],
['http://youtube.com/watch?v=uG3qt1F-LSY', 'Meg & Dia - Monster (DotEXE Dubstep Remix)'],
['http://youtube.com/watch?v=350x_9wY8nY', 'Shirk - Haunted'],
['http://youtube.com/watch?v=ZKAZ2oNnwdo', 'Different Heaven & EH!DE - My Heart'],
['http://youtube.com/watch?v=MIeOpQXMo-I', 'BasslineKicker - Wafture (djvoldex Remix)'],
['http://youtube.com/watch?v=GLhUIO-r_HE', 'Will & Tim - Song Of Storms'],
['http://youtube.com/watch?v=5NE6U860AZ0', 'nanobii - Pineapple Spaceship'],
['','** Gaming **'],
['', 'J and Sock Play Undertale'],
['www.youtube.com/watch?v=nMjNQ3AsjjU','Part 1 - Satin Ruins Everything: The Movie'],
['www.youtube.com/watch?v=CjGFPUauZ_w','Part 2 - Flash Forward'],
['www.youtube.com/watch?v=mJPzfkI4ZlQ','Part 3 - Bone-afied Boss Battle'],
['www.youtube.com/watch?v=lSjuLi79LvM','Part 4 - Intense Passion'],
['www.youtube.com/watch?v=4nqe9hlNT_k','Part 5 - rUN'],
['www.youtube.com/watch?v=42Dy8U2rZnQ','Part 6 - Through the Spears and Trash'],
['www.youtube.com/watch?v=oFluzFsRN08','Part 7 - hOI!!!'],
['www.youtube.com/watch?v=eT_r92SlTGs','Part 8 - Can I Ask You Something?'],
['www.youtube.com/watch?v=pjqG1mjguoY','Part 9 - Determined Repetition'],
['www.youtube.com/watch?v=eYjPOT0fYd8','Part 10 - Counterproductive'],
['www.youtube.com/watch?v=yyYF5a0lUv8','Part 11 - Puzzling!'],
['www.youtube.com/watch?v=Atil7672UA8','Part 12 - The Scoop'],
['www.youtube.com/watch?v=xIdMQk5DpNU','Part 13 - One True Love (Cover)'],
['www.youtube.com/watch?v=WyUKO4Zua9g','Part 14 - Core Encounters'],
['www.youtube.com/watch?v=ZmlQV-oGc_M','Part 15 - The Premiere'],
];

/* ----- CREATING DATABASE LAYOUT - DO NOT REMOVE ----- */

dbwrap = $('<div id="dbwrap" class="col-lg-12 col-md-12" style="display:none" />').insertBefore(configwrap);
dbwell = $('<div id="db-well" class="well" />').appendTo(dbwrap);

var item_nr=0;
var layer_nr=1;
var opening=new Array();
var item_count=new Array(0);
var count_nr=0;

if (ChannelDatabase.length<1 || ChannelDatabase[0][0]!="") {
	ChannelDatabase.unshift(['', '(various media)']);
}
UI_ChannelCache=="1" ? createDatabase() : '';

/* ----- END OF FILE ----- */
